# Cadastro de empresa
POST http://localhost:8080/empresa
content-type: application/json

{
  "cnpj": "14890437000152",
  "nomeEmpresa": "Andreia e Bianca Lavanderia Ltda"
}

### Lista empresa

GET http://localhost:8080/empresa


### prometheus

GET http://localhost:8080/actuator/prometheus