# Cadastro de empresa
POST http://localhost:8080/empresa
content-type: application/json

{
  "cnpj": "14890437000152",
  "nomeEmpresa": "Andreia e Bianca Lavanderia Ltda"
}

### Lista empresa

GET http://localhost:8080/empresa

### Get empresa

GET http://localhost:8080/empresa/14890437000152


### Consulta empresa na receita

GET http://localhost:8080/empresa/consulta_receita_federal/00360305000104


### prometheus

GET http://localhost:8080/actuator/prometheus