global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
      - prometheus:9090
 - job_name: 'empresa-app'
   metrics_path: '/actuator/prometheus'
   static_configs:
    - targets: 
      - 172.29.32.1:8080
